import Head from "next/head";


import Navbar from "../components/navbar";
import Sidebar from "../components/sidebar";


const Layout = ({ children }) => {
    return (
        <div>

            <Head>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <link rel="stylesheet" href="https://unicons.iconscout.com/release/v4.0.0/css/line.css" />
                <script src="https://cdn.tailwindcss.com"></script>
            </Head>

            <Navbar />

            <div className="flex flex-row p-6">

                <div>
                    <Sidebar />
                </div>

                <div className="px-20">
                    {children}
                </div>

            </div>

        </div>
    );
}


export default Layout;