import { Fragment } from "react";
import { Input, Button } from "@nextui-org/react";
import Head from "next/head";


import Navbar from "../components/navbar";


const Login = () => {
    return (
        <Fragment>

            <Head>
                <title>Login</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <link rel="stylesheet" href="https://unicons.iconscout.com/release/v4.0.0/css/line.css" />
                <script src="https://cdn.tailwindcss.com"></script>
            </Head>

            <Navbar />
            <div className="h-screen">
                <div className="flex h-4/5 items-center justify-center">

                    <form>

                        <div className="rounded-xl bg-purple-100 p-4 mb-8">
                            <h2 className="text-purple-400 text-lg font-medium">Login</h2>
                        </div>

                        <div className="space-y-10">

                            <div>
                                <Input color="secondary" fullWidth={true} clearable bordered labelPlaceholder="Email" type="email" />
                            </div>

                            <div>
                                <Input.Password fullWidth={true} color="secondary" clearable bordered labelPlaceholder="Password" type="password" />
                            </div>

                        </div>

                        <Button className="bg-purple-400 w-full mt-6">Login</Button>

                    </form>

                </div>
            </div>

        </Fragment>
    );
}


export default Login;